### ISSUE TITLE
Unable to run Docker file 

### ISSUE THREAD

**Issue by manojsitapara** [AlanMartines/mywhatsapp-api-node-baileys#1]
When I tried to run docker file, it throw following error

> internal/modules/cjs/loader.js:905
  throw err;
  ^

> Error: Cannot find module '/usr/src/mywhats-api/index.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }

Can you please help me to fix the issue?

**Comment by AlanMartines** [comment]
Estou ajustando esses detalhes...

**Comment by manojsitapara** [comment]
When I tried to run the docker image, it throw error, the reason behind why it throw error because of following line (Line number:8) in package.json file

`    "start": "node index.js",
`

the above code tries to run index.js file which is not exist in the project.

I hope this give you enough infomration.
